framework:
    secret: '%env(APP_SECRET)%'

    http_method_override: false
    handle_all_throwables: true

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    php_errors:
        log: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800  # 1 week (same as remember_me)
        gc_maxlifetime: 604800   # 1 week
        storage_factory_id: session.storage.factory.native

    uid:
        default_uuid_version: 7
        time_based_uuid_version: 7

    mailer:
        dsn: '%env(MAILER_DSN)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
